### PR TITLE
Sessions - day 1 - google translate: add challenge

### PR DESCRIPTION
**Pull request by kariem**

### CODE REVIEW

**Comment by friedger** [comment]
There is a link to it in the community keynote. Are these two different sessions?

**Comment by kariem** [comment]
I have removed the link from the 'community page' it should contain other stuff which I added to a todo

**Comment by friedger** [comment]
That looks better. However, the file names have changed. They should be updated in the summary.md.

**Comment by kariem** [comment]
Ok, removed the rename commits. Not really necessary :)

**Comment by friedger** [comment]
Great! Thanks for your contribution!

**Pull request merged**
